# Generated by Django 5.0.3 on 2024-12-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='content',
            new_name='coment',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='coment',
        ),
    ]
