# Generated by Django 5.0.3 on 2024-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_content_advertisement_coment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='telephone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='telephone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
