# Generated by Django 5.0.3 on 2024-12-14 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='delivery_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='delivery_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
